### PR TITLE
CI: Enable checkcommits.

### LINKED ISSUE #93: Add checkcommits support
This seems a bit incestuous, but the other repos are using `checkcommits`, thus so should the repo that hosts it ;-)

### PR DESCRIPTION
**Pull request by jodh-intel**
Run the checkcommits tool on all PRs (under TravisCI only).

Fixes #93.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Aieeee! This isn't going to work as the repo isn't configured for Travis yet.

@chavafg - can we do this?

**Comment by jodh-intel** [comment]
@chavafg - another thought: I could put `get_repo_slug()` in `setup_tests.sh` instead if you'd prefer?

**Comment by chavafg** [comment]
Let me check if I have the powers to add travis here

**Comment by chavafg** [comment]
Nop, no permissions to add travis, @sameo should have.

**Comment by chavafg** [comment]
@jodh-intel about `get_repo_slug` I'll prefer to have it in `setup_test.sh`, seems that it is going to be used there, right?

**Comment by jodh-intel** [comment]
@chavafg - done. It should be safe to merge this as it won't do anything until #95 is merged.

**Comment by jodh-intel** [comment]
Closing as this has be done on #96.

**Pull request closed without merging**
