### PR TITLE
ci: Add the fetch branches tool to CI

### LINKED ISSUE #121: Add fetch branches tool to ci scripts
Integrate the fetch branches tool to .ci/setup.sh

### PR DESCRIPTION
**Pull request by GabyCT**
Build and run the fetch branches tool as part of the setup.sh
of the .ci.

Fixes #121

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Looks like it failed on semaphore due to go-github not being installed.

**Comment by jodh-intel** [comment]
Yep, @GabyCT - you'll need to add that package to `vendor/` using the `dep` tool I think.

**Comment by GabyCT** [comment]
@grahamwhaley and @jodh-intel, I submitted the PR #141 in order to solve those issues. Thanks

**Comment by chavafg** [comment]
#141 already merged, so seems that this is not blocked anymore

**Comment by chavafg** [comment]
lgtm

**Comment by grahamwhaley** [comment]
lgtm
Looks like we need an approval review from @devimc to close this one.

**Comment by grahamwhaley** [comment]
hah, or me (it actually needed anybody with write perms). ... merging....

**Pull request merged**
