### PR TITLE
integration/docker: fix hot plug test

### LINKED ISSUE #728: Fix hotplug attach block device
The new hotplug tests introduced in `integration/docker` works well with the current agent, but with the most up to date version in the agent repo, we get those failures:
```
00:26:17.551 run hot plug a block device 
00:26:17.551   should be attached
00:26:17.551   /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/run_test.go:188
00:26:17.552 Running command '/bin/dd [dd if=/dev/zero of=/tmp/dd930285728 count=1 bs=5M]'
00:26:17.552 [dd if=/dev/zero of=/tmp/dd930285728 count=1 bs=5M]
00:26:17.552 Timeout: 60 seconds
00:26:17.552 Exit Code: 0
00:26:17.552 Stdout: 
00:26:17.552 Stderr: 1+0 records in
00:26:17.552 1+0 records out
00:26:17.552 5242880 bytes (5.2 MB, 5.0 MiB) copied, 0.00479688 s, 1.1 GB/s
00:26:17.552 
00:26:17.552 Running command '/bin/bash [bash -c printf "g\nn\n\n\n\nw\n" | fdisk /tmp/dd930285728]'
00:26:18.332 [bash -c printf "g\nn\n\n\n\nw\n" | fdisk /tmp/dd930285728]
00:26:18.332 Timeout: 60 seconds
00:26:18.332 Exit Code: 0
00:26:18.332 Stdout: 
00:26:18.332 Welcome to fdisk (util-linux 2.27.1).
00:26:18.332 Changes will remain in memory only, until you decide to write them.
00:26:18.332 Be careful before using the write command.
00:26:18.332 
00:26:18.332 Device does not contain a recognized partition table.
00:26:18.332 Created a new DOS disklabel with disk identifier 0x7f2667db.
00:26:18.332 
00:26:18.332 Command (m for help): Created a new GPT disklabel (GUID: 74013976-C8F9-4250-AB1A-5F84636033C9).
00:26:18.332 
00:26:18.332 Command (m for help): Partition number (1-128, default 1): First sector (2048-10206, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-10206, default 10206): 
00:26:18.332 Created a new partition 1 of type 'Linux filesystem' and of size 4 MiB.
00:26:18.332 
00:26:18.332 Command (m for help): The partition table has been altered.
00:26:18.332 Syncing disks.
00:26:18.332 
00:26:18.332 
00:26:18.332 Stderr: 
00:26:18.332 Running command '/usr/bin/partx [partx -av /tmp/dd930285728]'
00:26:18.377 command failed error 'exit status 1'
00:26:18.377 [partx -av /tmp/dd930285728]
00:26:18.377 Timeout: 60 seconds
00:26:18.377 Exit Code: 1
00:26:18.377 Stdout: partition: none, disk: /tmp/dd930285728, lower: 0, upper: 0
00:26:18.378 Trying to use '/dev/loop0' for the loop device
00:26:18.378 /dev/loop0: partition table type 'gpt' detected
00:26:18.378 
00:26:18.378 Stderr: partx: /dev/loop0: adding partition #1 failed: Device or resource busy
00:26:18.378 partx: /dev/loop0: error adding partition 1
00:26:18.378 
00:26:18.378 Running command '/usr/bin/docker [docker ps -a -f name=jtmfR2VYVw5l15x9pn42o8NI6VVtU1 --format {{.Status}}]'
00:26:18.392 [docker ps -a -f name=jtmfR2VYVw5l15x9pn42o8NI6VVtU1 --format {{.Status}}]
00:26:18.392 Timeout: 60 seconds
00:26:18.392 Exit Code: 0
00:26:18.392 Stdout: 
00:26:18.392 Stderr: 
00:26:18.407 Running command '/usr/bin/partx [partx -d ]'
00:26:18.408 command failed error 'exit status 1'
00:26:18.408 [partx -d ]
00:26:18.408 Timeout: 60 seconds
00:26:18.408 Exit Code: 1
00:26:18.408 Stdout: 
00:26:18.408 Stderr: partx: stat of  failed: No such file or directory
00:26:18.408 
00:26:18.409 
00:26:18.409 • Failure in Spec Setup (BeforeEach) [0.867 seconds]
00:26:18.409 run
00:26:18.409 /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/run_test.go:190
00:26:18.409   hot plug a block device [BeforeEach]
00:26:18.410   /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/run_test.go:189
00:26:18.410     should be attached
00:26:18.410     /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/run_test.go:188
00:26:18.410 
00:26:18.410     Expected error:
00:26:18.410         <*errors.errorString | 0xc420348340>: {
00:26:18.410             s: "partx: /dev/loop0: adding partition #1 failed: Device or resource busy\npartx: /dev/loop0: error adding partition 1\n",
00:26:18.410         }
00:26:18.410         partx: /dev/loop0: adding partition #1 failed: Device or resource busy
00:26:18.410         partx: /dev/loop0: error adding partition 1
00:26:18.410         
00:26:18.410     not to have occurred
00:26:18.411 
00:26:18.411     /home/jenkins/jenkins_slave/workspace/clear-containers-agent-azure-ubuntu-16-04-PR/go/src/github.com/clearcontainers/tests/integration/docker/run_test.go:169
```

I could not reproduce locally the issue, it might be related to something in the CI.

### PR DESCRIPTION
**Pull request by devimc**
use losetup to create loop devices

fixes #728

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@devimc have you tested this with latest agent locally ? I am asking because the CI here does not mean the issue with latest agent is fixed.

**Comment by devimc** [comment]
@sboeuf yes, I did it

**Comment by sboeuf** [comment]
@devimc cool thanks !
LGTM

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
