### PR TITLE
CI: support for Ubuntu 16

### PR DESCRIPTION
**Pull request by devimc**
Add support for Ubuntu 16

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Looks like semaphore has some broken PGPness right now - might have to retry that tormorrow maybe

**Comment by grahamwhaley** [comment]
oh, or actually, maybe that is an issue with the clear containers fetch repo?

**Comment by grahamwhaley** [comment]
lgtm
looks like Travis was happy. Just waiting to see if Semaphore survives :-)

**Comment by devimc** [comment]
yep, seems like semaphore is broken

**Comment by chavafg** [comment]
now everything looks good... merging

**Pull request merged**
