### PR TITLE
 tests: create a wrapper for docker commands

### LINKED ISSUE #374: integration/docker: create wrappers for docker commands
create wrappers for docker command to make integration test easier to write and maintain

### PR DESCRIPTION
**Pull request by devimc**
with this wrapper make tests will be easier because the user
will not be worry about the timeouts neither writing incorrectly
the name of the commands

Fixes #374

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@devimc as you are changing the scripts, could you please modify Ω to Expect so we have uniformity in all the scripts

**Comment by devimc** [comment]
@GabyCT sure

**Comment by devimc** [comment]
@GabyCT I'll do it in another pr

**Comment by GabyCT** [comment]
lgtm

**Comment by grahamwhaley** [comment]
thanks for the omega mods!

**Pull request merged**
