### PR TITLE
Add functional tests for start command 

### PR DESCRIPTION
**Pull request by devimc**
Add some functional tests for start command

### CODE REVIEW

**Comment by devimc** [comment]
https://github.com/clearcontainers/tests/pull/3

**Comment by devimc** [comment]
closing PR it should be part of https://github.com/clearcontainers/runtime

**Comment by devimc** [comment]
reopening it , after a discussion we decide that this repo will also have functional tests

**Comment by dlespiau** [comment]
should at least wait for a lgtm from someone :) let's do that for the next ones.

**Pull request merged**
