### PR TITLE
integration: crio: Add 2 more tests

### LINKED ISSUE #260: Add new CRI-O tests
With latest changes we made to our runtime and to hyperstart, we can add 2 more tests to the CRI-O bats:
- `ctr logging [tty=true]`
- `ctr execsync failure`

### PR DESCRIPTION
**Pull request by sboeuf**
With recent changes brought to the runtime and to hyperstart agent,
we can add two new tests from the CRI-O bats:
- ctr logging [tty=true]
- ctr execsync failure

Fixes #260

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@sboeuf I presume we are waiting for some changes in the other repos to land before we will see these tests pass?
Travis hit the annoying SHA not found issue, and it looks like you stopped semaphore yourself. Do we need a DNM or WIP label etc.?

**Comment by sboeuf** [comment]
@jcvenegas updated the hyperstart version and we need this to land into clear-containers.img. It's been a month that we have merged a patch for hyperstart but we never updated the hyperstart version in our image.

**Comment by jcvenegas** [comment]
The image 16660 now includes hyperstart changes  thttps://download.clearlinux.org/releases/16660/clear/RELEASENOTES

**Comment by sboeuf** [comment]
@grahamwhaley @chavafg This one is now passing :)

**Pull request merged**
