### PR TITLE
Get cc-tests dependencies

### PR DESCRIPTION
**Pull request by GabyCT**
Retrieve the repository of ginkgo in order to be able to run
the functional tests.

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
The main idea behind this PR is that once that this is merged https://github.com/clearcontainers/runtime/pull/195, this script will be run in semaphore in the ci of the runtime and I will add another PR to this tests repository that will be in charge of running the functional tests.

**Comment by devimc** [comment]
in this PR https://github.com/clearcontainers/tests/pull/38, I install ```ginkgo``` if it is not installed
could be an option to simplify the things

**Comment by devimc** [comment]
if #38 is accepted then ```.ci/install_cc_tests_dependencies.sh``` is not needed

**Comment by dlespiau** [comment]
It's a bit hard to know where we're going with just this part of the problem. it's really one line :)

We should try to solve the full "run the functional tests" in this kind of PR.

**Comment by GabyCT** [comment]
as PR #38 will do this, this is not need it anymore

**Pull request closed without merging**
