### PR TITLE
Checkcommits fix travis master build

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by dlespiau** [comment]
It'd be nice if this was covered by tests as well.

**Comment by jodh-intel** [comment]
Good call - I'll add some tests...

**Comment by jodh-intel** [comment]
Test code added.

**Comment by jodh-intel** [comment]
Could this be re-reviewed please? I need to chat to @jcvenegas, but I think the reason we've disabled `checkcommits` for `cc-oci-runtime` (https://github.com/01org/cc-oci-runtime/issues/967) is because this hasn't yet landed.

**Comment by jodh-intel** [comment]
@devimc, @sameo, @jcvenegas - I believe this fixes the `checkcommits` issue you saw under https://github.com/01org/cc-oci-runtime/pull/971.

Could you review so we can resolve and re-enable the tool for `cc-oci-runtime`?

**Comment by sameo** [comment]
LGTM

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
