### PR TITLE
run_all_metrics: detect script path

### PR DESCRIPTION
**Pull request by bwarden**
Add SCRIPT_PATH to run_all_metrics.sh script so it can execute
tests successfully from any location.

Signed-off-by: Brett T. Warden <brett.t.warden@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
@bwarden, can you please create an issue for the problem you are solving with this PR and add to the commit message a line with `Fixes #XYZ.` refering to the issue number that you created, so that travis-ci does not complain?

**Comment by bwarden** [comment]
Opened #168 for this. Do I need to amend the actual commit, the original comment in this thread, or just add it in this comment like so?

Fixes #168

**Comment by bwarden** [comment]
Alright, Travis doesn't like amended commits. I'll just open a new PR.

**Comment by grahamwhaley** [comment]
Hi @bwarden . You need to modify the commit itself, as that is what `checkcommits` checks on Travis. It cannot read the comments or merge message I'm afraid. I PR'd to update the CONTRIB file to make this clearer yesterday.
force pushing updates to the PR is our normal workflow (rather than adding extra patches to the PR or opening new PRs to replace existing ones). But, we have been seeing a couple of Travis issues recently:
 - sometimes if you force push 'too fast' Travis picks up the old commit and then we fail, and the only way we have found to get out of that is the close/re-open-new-PR path
 - Travis and checkcommits are currently having frequent debates with each other about which commit/branch needs checking. This is probably what you ran into. Force pushes clear that more times than not. We are working on figuring that one out...

**Pull request closed without merging**
