### PR TITLE
Install checkcommits binary

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @chavafg - it looks like Semaphore isn't configured correctly - it's trying to call `.ci/setup.sh` which doesn't exist.

**Comment by chavafg** [comment]
Oh right, that setting should exists after #45 is merged. Checking with @devimc

**Comment by devimc** [comment]
@jodh-intel could you please rebase your PR?

**Comment by jodh-intel** [comment]
@devimc - done.

**Comment by devimc** [comment]
lgtm

**Pull request merged**
