### PR TITLE
ci: Add proxy env variables to crio service.

### PR DESCRIPTION
**Pull request by jcvenegas**
Check proxy env variables are set and add them to
the crio service.

- Generate the crio service.

Fixes: #964

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Review by chavafg — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
The metrics CI is failing due to:

```
open results/network-bwd-host-contr-receiver.csv: no such file or directory
```

/cc @grahamwhaley.

**Comment by grahamwhaley** [comment]
Indeed @jodh-intel. If you look further back up the logs you will find:
```
12:09:59 ERROR: iperf server init fails
```
which directly relates to #960 where I diagnosed and explained the problem.
Until/unless somebody explains and justifies the change in the mount of `/dev/shm` to a 9p mount, then I don't see this as a metrics test failure - I see it as a break in our shm mount. Nobody has explained yet. Until we have settled what is the right thing to do with `shm` (and possibly other tmpfs/ramfs mounts), then I'm afriad this test, and thus the metrics, is going to remain broken...
 /cc @sboeuf @amshinde .

(Vaguely related is https://github.com/kata-containers/kata-containers/issues/21 I would say as well)

**Pull request closed without merging**
