### PR TITLE
tests: Add go-github for Semaphore

### LINKED ISSUE #138: vendor fetch branches tool dependencies
vendor fetch branches tool dependencies in order to merged the tool to the CI #122

### PR DESCRIPTION
**Pull request by GabyCT**
Vendor the go-github project in order to include the
fetch branches tool as part of the CI.
Fixes #138

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by grahamwhaley** [comment]
It looks like semaphore has got 'stuck' somehow on this. Any thoughts @GabyCT @devimc ?

**Comment by chavafg** [comment]
pullapprove complaining about vendored documentation. 
@GabyCT can you add the following line to: https://github.com/clearcontainers/tests/blob/master/.pullapprove.yml#L50 

```
 - "cmd/fetchbranches/vendor/*"
```

So that vendored documentation are excluded.
Not sure if we can use a regex there?

**Comment by GabyCT** [comment]
@chavafg changes applied :)

**Comment by chavafg** [comment]
Thanks @GabyCT. 
Still pullapprove is not happy yet, so we would need an approval from doc anyway.

@iphutch can you add your approval here? There is no documentation changes, but this PR is vendoring `go-github` which contains its own documentation.

Gaby already changed pullapprove configuration, but wont be effective until we merge it.

**Comment by GabyCT** [comment]
@iphutch could you please take a look

**Pull request merged**
